version: '2'
volumes: 
  cloud9-workspace:
  ssh-data:
services:
  cloud9:
    build: ./cloud9
    ports:
      - '8181:8181'
    volumes: 
      - 'cloud9-workspace:/workspace'
      - 'ssh-data:/root/.ssh'
    command: ["/bin/node", "/cloud9/server.js", "-p", "8181", "-w", "/workspace", "-l", "0.0.0.0", "-a", ":"]
    working_dir: /workspace
  ssh:
    build: ./ssh
    ports:
      - '22:22'
    volumes: 
      - 'cloud9-workspace:/workspace'
      - 'ssh-data:/root/.ssh'
    working_dir: /workspace