version: '3.4'
services:

    cloud9:
        image: klutchell/cloud9
        container_name: cloud9
        ports:
            - 8080:8080
        restart: unless-stopped
        volumes:
            - cloud9_home:/root
            - cloud9_workspace:/workspace
        environment:
            - TZ=America/Toronto
            - C9_USER=root
            - C9_PASS=cloud9
        privileged: true

volumes:
    cloud9_home:
    cloud9_workspace:
