version: '2'
volumes: 
  cloud9-workspace:
  ssh-data:
services:
  cloud9:
    build: ./cloud9
    ports:
      - '8181:8181'
    volumes: 
      - 'cloud9-workspace:/workspace'
      - 'ssh-data:/root/.ssh'
    working_dir: /workspace
    command: node server.js -w/workspace --listen 0.0.0.0 -a :
  ssh:
    build: ./ssh
    ports:
      - '22:22'
    volumes: 
      - 'cloud9-workspace:/workspace'
      - 'ssh-data:/root/.ssh'
    working_dir: /workspace