version: '2'

volumes: 
  cloud9-workspace:
  ssh-data:

services:

  cloud9:
    build: ./cloud9
    ports:
      - '80:8080'
    volumes: 
      - 'cloud9-workspace:/workspace'
      - 'ssh-data:/root/.ssh'

  ssh:
    build: ./ssh
    ports:
      - '22:22'
    volumes: 
      - 'cloud9-workspace:/workspace'
      - 'ssh-data:/root/.ssh'

